services:
  db:
    image: pgvector/pgvector:pg15
    container_name: knowthee-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=knowthee
    ports:
      - "5433:5432"                  # map container 5432 → host 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./knowthee-db/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d knowthee"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  ingest:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["python", "-m", "backend.services.ingest"]
    command: ["all"]
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/knowthee

volumes:
  postgres_data:
