services:
  db:
    image: pgvector/pgvector:pg15
    container_name: knowthee-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=knowthee
    ports:
      - "5433:5432"                  # map container 5432 → host 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./knowthee-db/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d knowthee"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knowthee-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DOCKER_ENV=true
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/knowthee
      - BACKEND_HOST=0.0.0.0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: ["uvicorn", "backend.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  ingest:
    build:
      context: .
      dockerfile: knowthee-db/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/knowthee
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  postgres_data:
